spring:
  jackson:
    time-zone: UTC

  datasource:
    url: jdbc:mysql://your-db-url?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: username
    password: userPassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  logging:
    level:
      org.hibernate.SQL: debug
      org.springframework.security: debug