name: LINDO Build Pipeline (PROD)

on: [push]

jobs:
  deploy-to-ecs:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: test
        id: test
        run: echo "Test"
